spring:
  main:
    web-environment: true
    show-banner: false
endpoints:
  health:
    sensitive: false
management:
  context-path: "/admin"
  metrics:
    export:
      jmx:
        domain: spring
    enable:
      jvm: false
      tomcat: false
      system: false
      process: false
server:
  port: 8008
# Elasticsearch
datasource-es:
  createIndexIfNotFound: true
  indexName: detector_mappings
  doctype: details
  detectorIndexName: detectors
  detectorDoctype: detector
  urls: localhost:9200
  config:
    connectionTimeout: 40000
    connectionRetryTimeout: 40000
    maxTotalConnection: 200

# Graphite metric source
graphite:
  urlTemplate: "http://graphiteUrl/render?from=-7d&format=json&maxDataPoints=2016&target=seriesByTag('{tags}')"
# Swagger documentation
swagger:
  service:
    version: "1.0.0"
    title: "Model service detector mappings"
    description: "API documentation for model service detector mappings"
